extern float32_t Input[];
extern float32_t Output[];
extern arm_cfft_radix2_instance_f32 fftS;
extern RCC_ClocksTypeDef RCC_Clocks;
extern volatile uint32_t prev_ms_timer;
extern volatile int midi_off_time;
extern volatile uint32_t local_time_ms;
extern volatile uint32_t ms_timer;
extern volatile int8_t all_initialized;
extern int do_test_mem;
extern int mem_test_cont;
extern int8_t do_play_midi;
extern volatile uint32_t tick_count;
extern volatile uint32_t LocalTime;
extern volatile int uptime_seconds;
extern volatile int prev_uptime_seconds;
extern volatile int fw_reset_time;
extern volatile int uptime_mod;
extern volatile int do_reset_flag;
extern volatile int8_t do_eth_init_tick;
extern volatile int do_print_prompt;
extern volatile int lwip_initialized;
extern volatile int check_firmware_update;
int should_do_tcp_poll PROTO ((void));
void do_system_reset PROTO ((void));
void save_config PROTO ((void));
void fft_shift (float32_t *data , int len );
void test_adc PROTO ((void));
void check_ms_timer PROTO ((void));
void do_main_tasks (int ltick );
void handle_ethernet (int ltick );
void handle_systick (void);
void assert_param (int pass );
