caddr_t _sbrk (int32_t incr );
int _close (int file );
extern char * __env[];
extern char * * environ;
int _execve (char *name , char **argv , char **env );
int _fork PROTO ((void));
int _fstat (int file , struct stat *st );
int _getpid PROTO ((void));
int _isatty (int file );
int _kill (int pid , int sig );
int _link (char *old , char *new );
void _exit (int status );
int _lseek (int file , int ptr , int dir );
int _open (const char *name , int flags , int mode );
int _read (int file , char *ptr , int len );
int _unlink (char *name );
int _wait (int *status );
int _write (int file , char *ptr , int len );
void abort PROTO ((void));
